name: Police
main: nlog\Police\Main
version: 1.0.0
author: nlog
api:
- 1.0.0
- 2.0.0
- 3.0.0-ALPHA5
- 3.0.0-ALPHA6

commands:
 police:
  permission: op
  description: 경찰 관련 명령어
 policecmd:
  permission: op
  description: 경찰이 사용할 수 있는 명령어 설정
